version: '3.1'

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - /root/mysql/data:/var/lib/mysql
        ports:
            - 33306:3306
        environment:
            MYSQL_ROOT_PASSWORD: mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8082:8080
